name: ci

on:
    push:
        branches: [ main, dev]
concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: run tests
              run: echo "running tests ...."