name: route-Cowsay

on: 
 push:
 workflow_dispatch:

jobs:
 ascii_job:
  runs-on: ubuntu-latest
  steps:
   
  - name: Checkout
    uses: actions/checkout@v7.0.1

  - name: run shell script
    run: 
     |
     chmod +x script.sh
     ./script.sh

  - name: list files
    run: 


 sec_job:
  runs-on: ubuntu-latest
  steps:

  - name: print
    run: echo "sec job"  
  


  