name: Cowsay 

on: push

jobs:
    Ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            
            - name: run shell script
              run:
                |
                chmod +x script.sh
                ./script.sh
                
