name: route-Cowsay

on: 
 push:
 workflow_dispatch:

jobs:
 ascii_job:
  # permissions:
  #  contents: Read
  #  packages: write
  runs-on: ubuntu-latest
  steps:
  - name: install Cowsay program
    run: sudo apt-get install cowsay -y

  - name: Execute Cowsay cmd
    run: cowsay -f dragon "Run for cover, iam a Dragon....RAWR" >> dragon.txt 

  - name: Test file exist
    run: grep -i "dragon" dragon.txt

  - name: Read file
    run: cat dragon.txt

  - name: checkout repo files
    run: ls
  

  