name: Cowsay UI/MOBILE 

on: 
  workflow_dispatch:
   inputs:
    action:
     description: "action to perform"
     required: true
     options:
     - scale

     env:
     type: choice
     options:
     - dev
     - staging
     - prod





jobs:
    Ascii_job:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            
            - name: give perm
              run: chmod +x script.sh
            - name: echo
              run: ./script.sh