name: firt wf

on: 
    pull_request:
    workflow_dispatch:


jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: print my name
              run: echo "ITI"
