name: Cowsay UI/MOBILE 

on: push


jobs:
    Ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            
            - name: give perm
              run: chmod +x script.sh
            - name: echo
              run: ./script.sh