name: firt wf

on: 
    pull_request:
        branches:
            - main
    workflow_dispatch:
    push:
        branches:
            - main


jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: print my name
              run: echo "ITI"
