name: matrix strategy

on:
 push:
 workflow_dispatch:

jobs:
 deploy-image:
  strategy:
   matrix:
    os: [ubuntu-latest, windows-latest, ubuntu-20]
    images: [hello-world, alpine]
    exclude:
    - images: alpine
      os: windows-latest
    include:
     - images: amd64/alpine
       os: ubuntu-latest

  runs-on: ${{ matrix.os }}
  steps:
   - name: echo docker details
     run: docker info

   - name: run image
     run: docker run ${{ matrix.images }}
  

