name: my first workflow | shell script
on: 
    push:
        branches:
            - main

jobs:
    hamada_job:
        runs-on: ubuntu-latest
        steps:
            - name: list files
              run:  echo "CICD"
