name: my first workflow | shell script
on: 
    push:
        branches:
            - main

jobs:
    hamada_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5.0.0

            - name: list files
              run:  |
               chmod +x script.sh
               ./script.sh
   
