name: exploring varaibles and screts
on:
    push
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: docker login
              run: docker login --username=20150748 --password=#tTesla2030#
