name: Exploring vars and secrets

on: push

jobs:
 
 docker:
  runs-on: ubuntu-latest
  steps:
   
  - name: docker login
    run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
