name: Exploring and secrets

on:
    push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: 20150748
    IMAGE_NAME: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        
        steps:
            - name: Docker Build
              
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
            
            - name: Docker Login
              env:
                DOCKER_PASSWORD: #Tesla2030#
              run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
        
            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/$CONTAINER_USERNAME/$IMAGE_NAME:latest
            
    deploy:
        needs: docker
        runs-on: ubuntu-latest 
        steps:
            - name: dicker run
              run: docker run -d -p 8080:80 docker.io/DOCKER_USERNAME/IMAGE_NAME:latest
              
              
        
        
        
        